### ISSUE TITLE
Path length analysis notebook has a missing figure

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gplugins#101]
**Describe the bug**
[Path length analysis notebook](https://gdsfactory.github.io/gplugins/notebooks/path_length_analysis.html) has a missing figure defined in
https://github.com/gdsfactory/gplugins/blob/3fa1a1e9871b985b5a406e4569e15de2d830cfc1/docs/notebooks/path_length_analysis.py#L81

**To Reproduce**
![image](https://github.com/gdsfactory/gplugins/assets/7860886/ce546f5d-d314-42f3-9a85-d16ca0de76bf)

**Expected behavior**
No missing figures

**Suggested fix**
Add figure to repo or imgur

**Comment by joamatab** [comment]
thank you Niko!

fixed here
https://github.com/gdsfactory/gplugins/commit/c5bccf1fa5eb1f68fc4834fbac20e5c74621b65a
