### ISSUE TITLE
dataprep crashing on big layouts

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#166]
When running a big layout through dataprep i see it crashing

[Process exited 139]

@sebastian-goeldi
@skandanc

**Comment by joamatab** [comment]
the solution was using the drc engine with tiling processor,

i think it would be great to support that for the dataprep plugin

@tvt173

**Comment by tvt173** [comment]
nice. would certainly be great to have the speedup if possible. out of curiosity though, do you know what that error is? an out of memory exception?

**Comment by joamatab** [comment]
it's a segmentation fault
