### ISSUE TITLE
Include layer connectivity information in PDK

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gplugins#179]
**Is your feature request related to a problem? Please describe.**
Currently, [netlist extraction etc](https://gdsfactory.github.io/gplugins/notebooks/11_get_netlist_spice.html). with `get_l2n` does not take layer-to-layer connectivity into account unless manually given a klayout technology file. This should probably be included in a PDK and then the active one used be fetched

**Describe the solution you'd like**
Add layer connectivity information to PDK and use it in `get_l2n`.

**Comment by joamatab** [comment]
You can get the technology object from the PDK after activating it

https://github.com/KLayout/klayout/issues/1223

**Comment by nikosavola** [comment]
gdsfactory part for this was done in https://github.com/gdsfactory/gdsfactory/pull/2179
