### ISSUE TITLE
path_length_analysis notebook issue

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#18]
the notebook has some issue 

https://gdsfactory.github.io/gplugins/notebooks/path_length_analysis.html

![image](https://github.com/gdsfactory/gplugins/assets/4514346/a1f027ec-4525-40a0-b319-8bcbfc4db802)

@tvt173

**Comment by tvt173** [comment]
is this after a recent change? the image in the notebook on the docs looks good and correct

**Comment by joamatab** [comment]
the image is a screenshot :) 

I don't know how to make bokeh display an image on the notebook

**Comment by tvt173** [comment]
ah, yeah I understand that part. i was just saying that the screenshot version in the notebook looks correct. so it looks like it was working at some point, and i was curious if you knew when it broke

**Comment by joamatab** [comment]
Im not sure but the tests were failing because gdsfactory/get_route was adding non serializable data, so i added clean_dict into it

**Comment by joamatab** [comment]
it looks fixed now
