### ISSUE TITLE
Use ruff instead of black

### ISSUE THREAD

**Issue by yaugenst** [gdsfactory/gplugins#236]
Now that ruff has a [built-in formatter](https://docs.astral.sh/ruff/formatter/) that is (mostly) identical to black, maybe we should use that instead? It's faster, but most of all it's one less dependency.

**Comment by joamatab** [comment]
PRs welcome :)

**Comment by joamatab** [comment]
fixed by https://github.com/gdsfactory/gplugins/pull/250
