### ISSUE TITLE
Show epsilon plot

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#243]
I find the epsilon plots more useful than current plots in ComponentModeller

before you can see nitride above

![image](https://github.com/gdsfactory/gplugins/assets/4514346/246c45cb-7927-484b-8f2c-16ef40748755)

now you can see one or the other

![image](https://github.com/gdsfactory/gplugins/assets/4514346/87c06d4c-b80b-4c3f-9fc4-58cdd7ddf82e)

@yaugenst

**Comment by yaugenst** [comment]
i believe the second plot is plotting the wrong x slice, bith layers should show uo

**Comment by joamatab** [comment]
i see,

this looks better now
![image](https://github.com/gdsfactory/gplugins/assets/4514346/ee9effb6-7041-4cf8-b1b3-246edf275004)

**Comment by yaugenst** [comment]
if you want to see both layers you need to plot somewhere other than the ports

**Comment by joamatab** [comment]
yes, the main issue is that td.ComponentModeler does not have `plot_eps` method

**Comment by yaugenst** [comment]
and it shouldn't because the component modeler does not know about materials, this is intentional

**Comment by joamatab** [comment]
fixed by https://github.com/gdsfactory/gplugins/pull/256
