### ISSUE TITLE
plot_e_all() calling plot_e without cmap

### ISSUE THREAD

**Issue by thomaslima** [gdsfactory/gplugins#246]
Any reason for this? That was unexpected for me.

https://github.com/gdsfactory/gplugins/blob/0622fb05adc340caf20c9c92980bc6e4046f0dc3/gplugins/modes/types.py#L289C45-L289C45

**Comment by joamatab** [comment]
We can change it , feel free to send a PR

**Comment by simbilod** [comment]
Good catch

Some of the history has been lost with the move to gplugins, more recently we have been relying more on [gdsfactory meshing](https://gdsfactory.github.io/gplugins/notebooks/meshing_03_2D_uz_mesh.html) + the [femwell mode solver](https://helgegehring.github.io/femwell/photonics/examples/waveguide_modes.html)

**Comment by thomaslima** [comment]
Thanks @simbilod !
