### ISSUE TITLE
Tidy3DComponent material type check

### ISSUE THREAD

**Issue by Paudet-ul** [gdsfactory/gplugins#259]
Is there a reason to limit Tidy3DComponent to only allow tidy3d.Medium type for materials? This limits the simulation to non-dispersive materials. In gplugin/tidy3d/types.py, it could allow all types of materials like PoleResidue, DispersiveMedium and so on. 

The check could be something like this:
```
module_classes = [
    cls for name, cls in vars(td.components.medium).items() if isinstance(cls, type)
]

# Function to validate the medium
def validate_medium(v):
    # Check if the input is an instance of td.components.medium types
    assert any(isinstance(
        v, cls
    ) for cls in module_classes), f"Input should be an instance {module_classes}, but got {type(v)} instead"
    return v
```

**Comment by joamatab** [comment]
Hi Pascal,

yes, we can do that, do you want to send a PR?

@yaugenst
