### ISSUE TITLE
fdtdz not showing in docs

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#303]
but is listed in the table of contents

![image](https://github.com/gdsfactory/gplugins/assets/4514346/b23ce86f-57af-43b0-9734-77a29736edb3)

@simbilod

**Comment by simbilod** [comment]
Do we have GPU runners now?

**Comment by joamatab** [comment]
not yet,
that's why we disabled the rendering

see fix here

https://github.com/gdsfactory/gplugins/pull/304

**Comment by simbilod** [comment]
Oh interesting, when we moved from Jupyterbook .py files back to ipynb it stopped including it

**Comment by joamatab** [comment]
yes, we had some `py` extensions there :)
