### ISSUE TITLE
improve dataprep

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#32]
- [ ] make layers lazy loaded
- [ ] Use tiling processor for klayout, so big layouts are fast to process
- [ ] Add options (flatten=False). By default at the moment it flattens, which inceases size of the GDS
- [ ] Write more exmples

https://gdsfactory.github.io/gplugins/notebooks/klayout_dataprep.html

@sunjin-choi
@skandanc
@tvt173 
@sebastian-goeldi

**Comment by tvt173** [comment]
A couple notes
- I think lazy-loading layers goes hand-in-hand with not flattening unnecessarily. I think operations should be on the flattened layers by default (it is the safest way), but we shouldn't overwrite a layer (and destroy the hierarchy) unless it is explicitly written to.
- It may be nice to add square bracket accessors too... So you can access a layer like `my_layout["WG"]` vs. `my_layout.WG` (as it is now).
