### ISSUE TITLE
PR broke tests

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#335]
![image](https://github.com/gdsfactory/gplugins/assets/4514346/e1dee4bf-5d2e-4596-bc1b-3e4b0cfeea75)

sorry for merging this

I enabled required_status_pass for the branch protection

@simbilod

**Comment by simbilod** [comment]
It was not obvious to me what broke since this PR only added a new flag to the gmsh plugin get_mesh function, I will have to dig deeper later

**Comment by joamatab** [comment]
It may also be Elmer tests failing :).  @nikosavola
