### ISSUE TITLE
new links extractor broke sax plugin

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#422]
new links extractor broke sax plugin

see ` test_mzi_lattice.py`

![Image](https://github.com/gdsfactory/gplugins/assets/4514346/8ac1405e-84bf-43e7-868f-82bd24d35a33)

@tvt173 
@flaport

**Comment by tvt173** [comment]
Yes, this is expected. Sax will need to parse "links" as it does with connections. The main difference is that links is a list of lists rather than a dict. Also, it will need to add compatibility for arrayed references

**Comment by joamatab** [comment]
This was fixed
