### ISSUE TITLE
Refactor Elmer examples to use `interdigital_capacitor_enclosed` from gdsfactory

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gplugins#49]
Refactor Elmer examples to use `interdigital_capacitor_enclosed` merged to main in https://github.com/gdsfactory/gdsfactory/pull/1994.
This includes
* docs
* tests

**Comment by nikosavola** [comment]
@joamatab, for this we need a new tagged version of gdsfactory

**Comment by joamatab** [comment]
I just released 7.3.2
