### ISSUE TITLE
FEMWELL - Unwanted geometry change from component creation to simulation

### ISSUE THREAD

**Issue by oz99** [gdsfactory/gplugins#493]
Originally found this bug in the PICtraining but believe it's due to the get_mesh.py file within gplugins.

Original issue was opened here:
https://github.com/gdsfactory/gdsfactory-photonics-training/issues/37

I'm using gdsfactory/FEMWELL to conduct mode simulations and the WG geometry returns an angled edge along the height of the structure when I haven't explicitly instructed this.

![image](https://github.com/user-attachments/assets/edd6f20c-ad2a-42fb-807e-0b42dd7c1c1e)

I specified the width of my straight WG to be 490nm. The width is 490nm at the center of the specified WG height. The bottom width of the WG is ~40nm larger while the top is around 40nm narrower. I also tried using a polygon with the same settings and this angle still appears in the simulation.

I can only achieve a normal angled (90 deg) edge in the simulation when defining the WG geometry purely in FEMWELL.

I don't believe this is a layerstack issue since when using the layerstack in the 3d viewer the structure has normal (90 deg) edges just before going into the FEMWELL simulation. 
![image](https://github.com/user-attachments/assets/802b0ca0-38a5-4f12-b0ed-5960b27f0d42)

I think this might be an issue with how the meshing within FEMWELL is inputting the component or layerstack inside the get_mesh.py file within gplugins.

Unsure what the suggested fix is, will do some more troubleshooting on the get_mesh.py file.

I'm using:
gplugins 1.1.2
GDSfactory 8.18.0
femwell 0.1.11 

Thanks, 
Oz

**Comment by joamatab** [comment]
See reply here
https://github.com/gdsfactory/gdsfactory-photonics-training/issues/37

**Comment by oz99** [comment]
Issue solved. 

Generic PDK has stock 10-degree sidewall angle in the layer stack.

Need to create a customized layer stack in gdsfactory or work directly with Femwell to define the needed anlge.
