### ISSUE TITLE
scalable way for testing and documenation

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#7]
as we increase the number of plugins, the tests and the documentation build time is going to increase

how can we run in paralel?

**Comment by HelgeGehring** [comment]
maybe just one job per plugin? (use build matrix and have the plugin name as the matrix-parameter)

**Comment by joamatab** [comment]
thank you Helge,

the tests run now in 3 minutes,

how would you paralelize testing the docs?

**Comment by HelgeGehring** [comment]
you can run the notebooks on a matrix one-by-one using jupyter-cache (I think, didn't use it directly yet): https://jupyter-cache.readthedocs.io/en/latest/using/api.html
we can read the notebook names using bash https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script to have them one-by-one in the matrix
