### ISSUE TITLE
port to pydantic>=2

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#73]
The core functionality is supported for pydantic2 now since release 0.4.0

However some other plugins are not available when using pydantic2

- [x] gdsfactory
- [x] gplugins https://github.com/gdsfactory/gplugins/pull/71 
- [ ] ray https://github.com/ray-project/ray/pull/39162
- [x] sqmodel https://github.com/tiangolo/sqlmodel/pull/632
- [x] dagster https://github.com/dagster-io/dagster/issues/15162

**Comment by sebastian-goeldi** [comment]
regarding ray: there is plan: https://github.com/ray-project/ray/issues/38977
