### ISSUE TITLE
HFSS plugin

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#81]
We already have a couple of Ansys plugins. How could we add RF design specific plugin using HFSS?

some examples:

- https://github.com/PhilReinhold/pyHFSS
- https://github.com/qiskit-community/qiskit-metal/tree/main/qiskit_metal/renderers/renderer_ansys

@nikosavola 
@zlatko-minev 
@jagandecapri

**Comment by nikosavola** [comment]
I think Ansys recommends this library nowadays https://github.com/ansys/pyaedt. Qiskit Metal uses pyEPR as a backend, which is very focused on superconducting qubits, maybe pyaedt could be mroe general?

**Comment by joamatab** [comment]
we should move it to the [gdsfactory plugins repo](https://gdsfactory.github.io/gplugins/)
